my_string = input("Введите фразу которой придерживайтесь по жизни: ")
print("Колличество символов в введенном тексте: ", len(my_string))
print("Строка в верхнем регистре: ", my_string.upper())
print("Строка в нижнем регистре: ", my_string.lower())
print(my_string.replace(" ",""))
print("Первый символ строки: ", my_string[0])
print("Последний символ строки:", my_string[-1])